Repository vegaprotocol/jenkins-shared-library, pull requests merged in 2022-11, with the labels that each got.

#317 fix: missing setup for Stagnet 2
  dsl/scripts/directories.groovy
  jcasc/scripts/init.sh
Labels: KTLO, no-issue

#286 fix: Provide full path to capsule config for system tests.
  vars/capsuleSystemTests.groovy
Labels: no-issue

#315 feat: use devopstools for stagnet3
  vars/pipelineDeployVegacapsule.groovy
  vars/withDevopstools.groovy
Labels: no-issue

#318 chore: Snapshot pipeline: use seeds and remove malformed entries
  vars/pipelineSnapshotTesting.groovy
Labels: KTLO, no-issue

#319 feat: add timeout to visor pipelines
  dsl/scripts/jobs.groovy
  vars/pipelineVegavisorManageNetwork.groovy
  vars/pipelineVegavisorManageNode.groovy
  vars/pipelineVegavisorProtocolUpgradeNetwork.groovy
  vars/pipelineVegavisorTopupBots.groovy
Labels: KTLO, no-issue

#320 feat: make vegatools difftool step as optional in the system tests
  vars/capsuleSystemTests.groovy
Labels: no-issue

#321 feat: enable validator joining and leaving on the devnet1
  dsl/scripts/jobs.groovy
  vars/pipelineVegavisorManageNode.groovy
  vars/vegautils.groovy
Labels: no-issue

#330 fix: fix the post-always-action
  vars/pipelineCapsuleSystemTests.groovy
Labels: no-issue

#332 chore: don't deploy faucet, cos it conflicts parallel task
  vars/pipelineVegavisorManageNetwork.groovy
Labels: KTLO, no-issue

#331 chore: send ethereum events for validator joining and leaving
  vars/pipelineVegavisorManageNode.groovy
Labels: KTLO, no-issue

#333 chore: update approbation version
  dsl/scripts/jobs.groovy
Labels: no-issue

#334 feat: update jenkins agent to v0.2.0
  jcasc/jenkins.yaml
Labels: no-issue

#335 chore: make approbation always run on latest
  dsl/scripts/jobs.groovy
Labels: no-issue

#325 feat: Use capsule_config_network_infra.hcl for lnl smoke tests to cat…
  vars/pipelineCapsuleSystemTests.groovy
Labels: no-issue

#340 fix: pass the correct release version to ansible
  vars/pipelineVegavisorManageNode.groovy
  vars/pipelineVegavisorProtocolUpgradeNetwork.groovy
Labels: KTLO

#342 feat: vega market sim reinforcement
  dsl/scripts/jobs.groovy
  vars/pipelineVegaMarketSim.groovy
Labels: no-issue
