Repository vegaprotocol/jenkins-shared-library, pull requests merged in 2023-02, with the labels that each got.

#391 chore: run bots Top-Up every 6 hours for Stagnet 3
  dsl/scripts/jobs.groovy
Labels: KTLO

#393 chore: change the way the Snapshot pipeline finds a server for config
  vars/pipelineSnapshotTesting.groovy
Labels: KTLO, no-issue

#394 chore: use data from data-node in Tendermint statesync config
  vars/pipelineSnapshotTesting.groovy
Labels: KTLO, no-issue

#395 chore: don't wait for vegawallet in Protocol Upgrade pipeline
  vars/pipelineVegavisorProtocolUpgradeNetwork.groovy
Labels: KTLO

#397 fix: move random section for Manage-Node pipeline
  vars/pipelineVegavisorManageNode.groovy
Labels: KTLO, no-issue

#398 fix: delay to disable the alert must be greater than 0
  vars/alert.groovy
  vars/pipelineVegavisorManageNetwork.groovy
  vars/pipelineVegavisorManageNode.groovy
Labels: KTLO, no-issue

#399 Disable alerts add basic auth
  vars/alert.groovy
Labels: KTLO, no-issue

#400 chore: top up bots on Stagnet 1 once an hour
  dsl/scripts/jobs.groovy
Labels: KTLO, no-issue

#403 chore: disable backing up snapshots for Fairground network
  dsl/scripts/jobs.groovy
Labels: KTLO, no-issue

#407 chore: update pv-snapshot-all to use vega binary to list snapshots an…
  resources/bin/pv-snapshot-all
Labels: no-issue

#408 chore: disable automatic protocol upgrade for Stagnet 3
  dsl/scripts/jobs.groovy
Labels: KTLO, no-issue

#411 chore: re-enable cron for Protocol Upgrade on Stagnet 1
  dsl/scripts/jobs.groovy
  vars/pipelineVegavisorProtocolUpgradeNetwork.groovy
Labels: KTLO, no-issue

#415 chore: disable automated Protocol Upgrade on Stagnet 3
  dsl/scripts/jobs.groovy
Labels: KTLO, no-issue

#417 chore: move node selection to be the first parameter to select
  dsl/scripts/jobs.groovy
Labels: KTLO, no-issue
