Repository vegaprotocol/jenkins-shared-library, pull requests merged in 2024-01, with the labels that each got.

#725 chore: add new parameter to choose default product used across system…
  dsl/scripts/jobs.groovy
  vars/capsuleSystemTests.groovy
  vars/pr.groovy
Labels: ci

#724 fix: correct the GITHUB TOKEN
  .github/workflows/add_issue_to_project.yml
Labels: devops, no-issue

#726 chore: updates version of approbation to the latest
  dsl/scripts/jobs.groovy
Labels: no-issue

#727 chore: check core unit tests for AC coverage
  dsl/scripts/jobs.groovy
Labels: no-issue
